version: '3.9'

services:
  atmosphereui:
    hostname: atmosphereapp.ru
    container_name: atmosphereui
    build:
      context: ./
      dockerfile: docker/Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - atmosphereui_bridge

networks:
  atmosphereui_bridge:
    driver: bridge
